services:
  mariadb:
    image: mariadb:10.11
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - abuse
    ports:
      - "9306:3306"

  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - abuse
    depends_on:
      - mariadb
    volumes:
      - ./phpunit.xml:/code/phpunit.xml
      - ./src:/code/src
      - ./tests:/code/tests

networks:
  abuse: